### ISSUE TITLE
3D case for the MARAUDER_SPOOF

### ISSUE THREAD

**Issue by Gino-Tonic** [ElectronicCats/flipper-shields#2]
Hi 

I have designed a 3D case for the MARAUDER_SPOOF - if you want to add it to your repository...

Thanks for a great device!

[3D_case_Marauder_spoof.zip](https://github.com/ElectronicCats/flipper-shields/files/12371008/3D_case_Marauder_spoof.zip)

**Comment by Gino-Tonic** [comment]
![image](https://github.com/ElectronicCats/flipper-shields/assets/133790287/544f1859-d4f5-41ec-8b95-eb310e7a8e84)

**Comment by xpeqex** [comment]
@Gino-Tonic 

Excellent implementation, thank you for sharing the picture!

We will have to print some at the office and test the add-on along with the case.

Thank you for your support and your time for sharing this with us.

Feel free to reach out to us again in case you have any queries!

**Comment by xpeqex** [comment]
Hi @Gino-Tonic 

I'm glad to inform you that we have added a link to this issue in the [Marauder Spoof wiki](https://github.com/ElectronicCats/flipper-shields/wiki/Flipper-Add-On:-Marauder-Spoof#need-a-case-for-your-marauder-spoof-shield), so the community can download and print your 3D design.
